FROM nginx:alpine
WORKDIR /app
RUN apk add nodejs
RUN apk add yarn
COPY package.json ./
RUN yarn install
COPY . ./
EXPOSE 80
CMD node /app/config.js && yarn build && cp -r /app/build/* /usr/share/nginx/html && nginx -g 'daemon off;'
