# Deployment for the auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      name: auth-pod
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-container
          image: beepchat/beep-auth-service:dep-less
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: auth-cont-port
          envFrom:
            - configMapRef:
                name: auth-svc-cfg
---
# auth-service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: auth-pod
