apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-svc-cfg
data:
  PORT: "80"
  COOKIE_DOMAIN: .beepchat.com
  DATABASE_HOST: auth-db-service
  DATABASE_PASSWORD: pwd
  DATABASE_USER: postgres
  DATABASE: authdb
  DATABASE_PORT: "80"
  REDIS_URL: redis://auth-cache-service:80
  AFTER_LOGIN_REDIRECT_URI: http://beepchat.com
  CLIENT_ID: 176671414954-uco1a20qgh6390l9p61d2hsib8fthjgv.apps.googleusercontent.com
  CLIENT_SECRET: mFuY73CM825fuPC1gyAt8Yrp
  JWT_SECRET: Hsd0F6-_nzSrSiFbaP
  GOOGLE_USER_EMAIL_SCOPE: https://www.googleapis.com/auth/userinfo.email
  GOOGLE_USER_PROFILE_SCOPE: https://www.googleapis.com/auth/userinfo.profile
  AUTH_REDIRECT_URI: http://auth.beepchat.com/a/login/google/callback
