version: "3"
services:
  loadbalancer:
    image: nginx:alpine
    volumes:
      - ./configs/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - static-service

  static-service:
    build:
      context: ./static-service
      dockerfile: Dockerfile.prod
    volumes:
      - files:/usr/share/nginx/files

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.prod
    environment:
      PORT: 4001
      DATABASE_HOST: auth-db
      DATABASE_PASSWORD: pwd
      DATABASE_USER: postgres
      DATABASE: authdb
      DATABASE_PORT: 5432
      REDIS_URL: redis://authcache
      AFTER_LOGIN_REDIRECT_URI: http://localhost:4000
      CLIENT_ID: 176671414954-gcdpafpbdqceelqfdi46dg54arbldibk.apps.googleusercontent.com
      CLIENT_SECRET: owFoBlYLWRDmFRcIAY3WFUP_
      JWT_SECRET: Hsd0F6-_nzSrSiFbaP
      GOOGLE_USER_EMAIL_SCOPE: https://www.googleapis.com/auth/userinfo.email
      GOOGLE_USER_PROFILE_SCOPE: https://www.googleapis.com/auth/userinfo.profile
      AUTH_REDIRECT_URI: http://localhost:4000/auth/a/login/google/callback
    expose:
      - 4001

    depends_on:
      - auth-db
      - auth-cache

  auth-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
      POSTGRES_DB: authdb
    volumes:
      - authdb:/var/lib/postgresql/data
    expose:
      - 5432

  auth-cache:
    image: redis:alpine
    container_name: authcache
    expose:
      - 6379

  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile.prod
    volumes:
      - files:/app/files
    environment:
      FILE_SERVICE_PORT: 4002
      AUTH_SERVICE_URL: http://auth-service:4001
      FILES_HOST: http://localhost:4000/files

    ports:
      - "4002:4002"

  beep-socket-service:
    build:
      context: ./beep-socket-service
      dockerfile: Dockerfile.prod
    environment:
      BEEP_SOCKET_SERVICE_PORT: 4003
      BEEP_SOCKET_SERVICE_DBHOST: socket-db
      BEEP_SOCKET_SERVICE_DBPASSWORD: pwd
      BEEP_SOCKET_SERVICE_DBUSER: postgres
      BEEP_SOCKET_SERVICE_DB: socketdb
      BEEP_SOCKET_SERVICE_DBPORT: 5433
      AUTH_SERVICE_URL: http://auth-service:4001
    ports:
      - "4003:4003"
    depends_on:
      - socket-db

  socket-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
      POSTGRES_DB: socketdb
      POSTGRES_PORT: 5433
    volumes:
      - socketdb:/var/lib/postgresql/data
    expose:
      - 5433
    command: -p 5433

  client-service:
    image: docker.io/beepchat/beep-web-client:dep-less
    environment:
      FILE_SERVICE_HOST: http://localhost:4002
      AUTH_SERVICE_HOST: http://localhost:4000/auth
      SOCKET_SERVICE_HOST: http://localhost:4003

volumes:
  authdb:
  files:
  socketdb:
