FROM nginx:alpine
WORKDIR /app
RUN apk add nodejs
RUN apk add yarn
COPY . ./
EXPOSE 80
CMD yarn install && node /app/config.js && yarn build && rm -r node_modules && cp -r /app/build/* /usr/share/nginx/html && nginx -g 'daemon off;'
