apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service-deployment
  labels:
    app: file-service-deployment
spec:
  selector:
    matchLabels:
      app: file-pod
  template:
    metadata:
      name: file-pod
      labels:
        app: file-pod
    spec:
      containers:
        - name: file-container
          image: beepchat/beep-file-service:dep-less
          ports:
            - containerPort: 80
              name: file-cont-port
          env:
            - name: FILE_SERVICE_PORT
              value: "80"
            - name: AUTH_SERVICE_URL
              value: http://auth-service:80
            - name: FILES_HOST
              value: http://static.beepchat.com
          volumeMounts:
            - name: files-vol
              mountPath: /app/files
      volumes:
        - name: files-vol
          persistentVolumeClaim:
            claimName: files-persistent-volume-claim
---
# file-service
apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: file-pod
